import { GenerationMode } from '../types/ai';

export function buildPrompt(content: string, mode: GenerationMode): string {
  const trimmed = content.trim();

  if (mode === 'summary') {
    return [
      'You are an expert professor creating DETAILED study summaries for university students.',
      'Analyze these lecture notes and create a comprehensive summary.',
      '',
      'Return EXACTLY this structure:',
      '📋 EXECUTIVE SUMMARY (3-4 sentences)',
      '',
      '🔑 KEY CONCEPTS (8-12 bullets):',
      '- Concept 1: [detailed explanation]',
      '',
      '⚠️ IMPORTANT FORMULAS / DEFINITIONS:',
      '',
      '💡 PRACTICAL APPLICATIONS:',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'questions') {
    return [
      'You are a university professor creating REAL EXAM questions.',
      'Generate COMPREHENSIVE practice questions from these notes.',
      '',
      'Return EXACTLY this format (10-12 questions):',
      '',
      '=== MULTIPLE CHOICE (4 questions) ===',
      '1. [Clear question]',
      '   A) [option]',
      '   B) [option]',
      '   C) [option] *(correct)*',
      '   D) [option]',
      '',
      '=== SHORT ANSWER (4 questions) ===',
      '5. [2-3 sentence answer expected]',
      '',
      '=== CONCEPTUAL (3 questions) ===',
      '9. Explain the relationship between X and Y...',
      '',
      '=== APPLICATION (2 questions) ===',
      '12. Given scenario X, how would you apply concept Y?',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'flashcards') {
    return [
      'You are an expert educator creating effective flashcards for spaced repetition learning.',
      'Generate EXACTLY 12 high-quality flashcards from these notes.',
      '',
      'CRITICAL: Return ONLY valid JSON. No markdown, no code blocks, no extra text.',
      'Start with { and end with }. Every field must be a string.',
      '',
      'Return EXACTLY this JSON format:',
      '{',
      '  "flashcards": [',
      '    {',
      '      "front": "Question or term (very clear and concise)",',
      '      "back": "Complete answer or definition (detailed but readable)",',
      '      "difficulty": "easy"',
      '    }',
      '  ]',
      '}',
      '',
      'IMPORTANT:',
      '1. Do NOT include markdown code blocks or ```',
      '2. Do NOT add any text before or after the JSON',
      '3. Each flashcard MUST have front, back, and difficulty fields',
      '4. Difficulty should always be "easy", "medium", or "hard" (only one)',
      '5. Use \\n for line breaks in back field if needed',
      '6. Make sure all quotes are properly escaped',
      '',
      'Guidelines:',
      '- Front: clear question (10-20 words max)',
      '- Back: detailed answer (2-4 sentences)',
      '- Mix of easy (40%), medium (35%), hard (25%) difficulty',
      '- Cover main concepts, important formulas, key relationships',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'quiz') {
    return [
      'You are a university professor creating a comprehensive quiz from these notes.',
      'Generate a 10-question multiple-choice quiz.',
      '',
      'Return EXACTLY this JSON format:',
      '{',
      '  "quiz": {',
      '    "title": "Quiz Title",',
      '    "questions": [',
      '      {',
      '        "question": "Clear question text",',
      '        "options": ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],',
      '        "correctAnswer": 0,',
      '        "explanation": "Why this is correct",',
      '        "difficulty": "easy|medium|hard"',
      '      },',
      '      ...',
      '    ]',
      '  }',
      '}',
      '',
      'Guidelines:',
      '- Questions should test understanding, not just memorization',
      '- Include 3-4 easy, 4-5 medium, 2-3 hard questions',
      '- Options should be plausible but clearly distinguishable',
      '- Explanations should be educational',
      '- Cover key concepts from all parts of the notes',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'mindmap') {
    return [
      '🧠 YOU ARE A MIND MAP GENERATION EXPERT',
      'Create a COMPLETE, HIERARCHICAL, MULTI-LEVEL mind map for effective learning.',
      '',
      '⚠️ CRITICAL OUTPUT RULES:',
      '1. Output MUST be PURE JSON - no markdown, no ```json blocks, no extra text',
      '2. Start with { and end with }',
      '3. Every string must be properly quoted',
      '4. No trailing commas',
      '5. ALL fields are REQUIRED',
      '',
      '📋 EXACT JSON FORMAT TO RETURN:',
      '{',
      '  "mindmap": {',
      '    "title": "Complete Topic Title",',
      '    "central": "Core Concept (3-5 words)",',
      '    "nodes": [',
      '      {',
      '        "id": "branch1",',
      '        "label": "Main Concept 1",',
      '        "description": "Clear explanation of this concept",',
      '        "icon": "concept",',
      '        "children": [',
      '          {',
      '            "id": "branch1-1",',
      '            "label": "Sub-concept A",',
      '            "description": "Important details here",',
      '            "icon": "definition",',
      '            "children": [',
      '              {',
      '                "id": "branch1-1-1",',
      '                "label": "Specific Detail",',
      '                "description": "Detailed information",',
      '                "icon": "example",',
      '                "children": []',
      '              }',
      '            ]',
      '          },',
      '          {',
      '            "id": "branch1-2",',
      '            "label": "Sub-concept B",',
      '            "description": "More key information",',
      '            "icon": "process",',
      '            "children": []',
      '          }',
      '        ]',
      '      }',
      '    ]',
      '  }',
      '}',
      '',
      '🎯 STRUCTURE REQUIREMENTS (MANDATORY):',
      '✓ Create EXACTLY 5-7 main branches (level 1)',
      '✓ Each main branch MUST have 3-5 children (level 2)',
      '✓ At least 3 branches MUST have level 3 children (2-3 each)',
      '✓ Use varied icons: concept, definition, example, process, important, warning, tip',
      '✓ Labels: 3-8 words, clear and specific',
      '✓ Descriptions: 10-30 words, educational and informative',
      '✓ IDs: use pattern "branch1", "branch1-1", "branch1-1-1"',
      '',
      '📚 CONTENT ORGANIZATION:',
      'Branch 1: Core Definitions and Terms',
      'Branch 2: Key Concepts and Theories',
      'Branch 3: Important Processes/Steps',
      'Branch 4: Examples and Applications',
      'Branch 5: Related Topics/Context',
      'Branch 6: Common Mistakes/Warnings (if applicable)',
      'Branch 7: Advanced Topics (if applicable)',
      '',
      '🎨 ICON USAGE GUIDE:',
      '- "concept" for theories, main ideas',
      '- "definition" for terms, terminology',
      '- "example" for use cases, examples',
      '- "process" for steps, procedures, methods',
      '- "important" for critical facts, key points',
      '- "warning" for errors, pitfalls to avoid',
      '- "tip" for helpful hints, mnemonics',
      '',
      '✅ QUALITY CHECKLIST:',
      '□ All nodes have id, label, description, icon, children',
      '□ No empty descriptions',
      '□ Hierarchical structure (3 levels minimum)',
      '□ Comprehensive coverage of ALL notes',
      '□ Educational and clear language',
      '□ Valid JSON with no syntax errors',
      '',
      '📝 ANALYZE THESE NOTES AND CREATE THE MIND MAP:',
      trimmed,
      '',
      '🚀 NOW GENERATE THE COMPLETE MIND MAP JSON (remember: NO markdown, NO code blocks, PURE JSON only):',
    ].join('\n');
  }
  return [
    'You are an expert study coach creating DETAILED 7-day study plans.',
    'Analyze these notes and create a comprehensive schedule.',
    '',
    'Return EXACTLY this structure:',
    '',
    '🎯 LEARNING OBJECTIVE',
    '[One clear sentence about what student will master]',
    '',
    '📅 7-DAY STUDY SCHEDULE',
    'Day 1: [3 hours] Focus + Method + Resources',
    'Day 2: [3 hours] ...',
    'Day 3: Review + Practice',
    'Day 4-6: Deep dive',
    'Day 7: Mock exam + Review',
    '',
    '📚 REQUIRED RESOURCES',
    '- Videos: [YouTube links]',
    '- Readings: [textbook chapters]',
    '',
    '✅ SUCCESS METRICS',
    '- [ ] Can explain X without notes',
    '- [ ] Solve Y problems',
    '',
    'Notes:',
    trimmed,
  ].join('\n');
}
