import { GenerationMode } from '../types/ai';

export function buildPrompt(content: string, mode: GenerationMode): string {
  const trimmed = content.trim();

  if (mode === 'summary') {
    return [
      'You are an expert professor creating DETAILED study summaries for university students.',
      'Analyze these lecture notes and create a comprehensive summary.',
      '',
      'Return EXACTLY this structure:',
      '📋 EXECUTIVE SUMMARY (3-4 sentences)',
      '',
      '🔑 KEY CONCEPTS (8-12 bullets):',
      '- Concept 1: [detailed explanation]',
      '',
      '⚠️ IMPORTANT FORMULAS / DEFINITIONS:',
      '',
      '💡 PRACTICAL APPLICATIONS:',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'questions') {
    return [
      'You are a university professor creating REAL EXAM questions.',
      'Generate COMPREHENSIVE practice questions from these notes.',
      '',
      'Return EXACTLY this format (10-12 questions):',
      '',
      '=== MULTIPLE CHOICE (4 questions) ===',
      '1. [Clear question]',
      '   A) [option]',
      '   B) [option]',
      '   C) [option] *(correct)*',
      '   D) [option]',
      '',
      '=== SHORT ANSWER (4 questions) ===',
      '5. [2-3 sentence answer expected]',
      '',
      '=== CONCEPTUAL (3 questions) ===',
      '9. Explain the relationship between X and Y...',
      '',
      '=== APPLICATION (2 questions) ===',
      '12. Given scenario X, how would you apply concept Y?',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'flashcards') {
    return [
      'You are an expert educator creating effective flashcards for spaced repetition learning.',
      'Generate EXACTLY 12 high-quality flashcards from these notes.',
      '',
      'CRITICAL: Return ONLY valid JSON. No markdown, no code blocks, no extra text.',
      'Start with { and end with }. Every field must be a string.',
      '',
      'Return EXACTLY this JSON format:',
      '{',
      '  "flashcards": [',
      '    {',
      '      "front": "Question or term (very clear and concise)",',
      '      "back": "Complete answer or definition (detailed but readable)",',
      '      "difficulty": "easy"',
      '    }',
      '  ]',
      '}',
      '',
      'IMPORTANT:',
      '1. Do NOT include markdown code blocks or ```',
      '2. Do NOT add any text before or after the JSON',
      '3. Each flashcard MUST have front, back, and difficulty fields',
      '4. Difficulty should always be "easy", "medium", or "hard" (only one)',
      '5. Use \\n for line breaks in back field if needed',
      '6. Make sure all quotes are properly escaped',
      '',
      'Guidelines:',
      '- Front: clear question (10-20 words max)',
      '- Back: detailed answer (2-4 sentences)',
      '- Mix of easy (40%), medium (35%), hard (25%) difficulty',
      '- Cover main concepts, important formulas, key relationships',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'quiz') {
    return [
      'You are a university professor creating a comprehensive quiz from these notes.',
      'Generate a 10-question multiple-choice quiz.',
      '',
      'Return EXACTLY this JSON format:',
      '{',
      '  "quiz": {',
      '    "title": "Quiz Title",',
      '    "questions": [',
      '      {',
      '        "question": "Clear question text",',
      '        "options": ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],',
      '        "correctAnswer": 0,',
      '        "explanation": "Why this is correct",',
      '        "difficulty": "easy|medium|hard"',
      '      },',
      '      ...',
      '    ]',
      '  }',
      '}',
      '',
      'Guidelines:',
      '- Questions should test understanding, not just memorization',
      '- Include 3-4 easy, 4-5 medium, 2-3 hard questions',
      '- Options should be plausible but clearly distinguishable',
      '- Explanations should be educational',
      '- Cover key concepts from all parts of the notes',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }

  if (mode === 'mindmap') {
    return [
      'You are an expert educator creating visual mind maps from lecture notes.',
      'Generate a COMPREHENSIVE hierarchical mind map structure from these notes.',
      '',
      'CRITICAL: Return ONLY valid JSON. No markdown, no code blocks, no extra text.',
      'Start with { and end with }.',
      '',
      'Return EXACTLY this JSON format:',
      '{',
      '  "mindmap": {',
      '    "title": "Study Mind Map",',
      '    "central": "Main Topic - The core concept",',
      '    "nodes": [',
      '      {',
      '        "id": "1",',
      '        "label": "First Main Branch",',
      '        "description": "Brief explanation of this branch",',
      '        "icon": "concept",',
      '        "children": [',
      '          {',
      '            "id": "1-1",',
      '            "label": "Subtopic 1",',
      '            "description": "Details about subtopic",',
      '            "children": []',
      '          },',
      '          {',
      '            "id": "1-2",',
      '            "label": "Subtopic 2",',
      '            "description": "More details",',
      '            "children": []',
      '          }',
      '        ]',
      '      },',
      '      {',
      '        "id": "2",',
      '        "label": "Second Main Branch",',
      '        "description": "Description here",',
      '        "icon": "definition",',
      '        "children": [...]',
      '      }',
      '    ]',
      '  }',
      '}',
      '',
      'Icon options: concept, definition, example, process, important, warning, tip, default',
      '',
      'Guidelines:',
      '- "central" is the MAIN TOPIC at the center of the mind map',
      '- Create 4-6 main branches (nodes with children)',
      '- Each main branch should have 2-4 subtopics',
      '- Include descriptions for each node (1-2 sentences)',
      '- Use appropriate icons for node types',
      '- Keep labels concise (3-6 words)',
      '- Cover ALL important concepts from the notes',
      '- Make the structure comprehensive and educational',
      '',
      'Notes:',
      trimmed,
    ].join('\n');
  }
  return [
    'You are an expert study coach creating DETAILED 7-day study plans.',
    'Analyze these notes and create a comprehensive schedule.',
    '',
    'Return EXACTLY this structure:',
    '',
    '🎯 LEARNING OBJECTIVE',
    '[One clear sentence about what student will master]',
    '',
    '📅 7-DAY STUDY SCHEDULE',
    'Day 1: [3 hours] Focus + Method + Resources',
    'Day 2: [3 hours] ...',
    'Day 3: Review + Practice',
    'Day 4-6: Deep dive',
    'Day 7: Mock exam + Review',
    '',
    '📚 REQUIRED RESOURCES',
    '- Videos: [YouTube links]',
    '- Readings: [textbook chapters]',
    '',
    '✅ SUCCESS METRICS',
    '- [ ] Can explain X without notes',
    '- [ ] Solve Y problems',
    '',
    'Notes:',
    trimmed,
  ].join('\n');
}
